/** @type {import('prettier').Config} */
module.exports = {
    endOfLine: "lf",
    semi: false,
    singleQuote: false,
    tabWidth: 2,
    trailingComma: "es5",
    plugins: ['@ianvs/prettier-plugin-sort-imports'],
    importOrder: [
      "^(react/(.*)$)|^(react$)",
      "^(next/(.*)$)|^(next$)",
      "<THIRD_PARTY_MODULES>",
      "",
      "^types$",
      "^@/types/(.*)$",      
      "^@/lib/(.*)$",
      "^@/data/(.*)$",
      "^@/ui/(.*)$",      
      "^@/verifications/(.*)$",      
      "^@/app/(.*)$",
      "",
      "^[./]",
    ],
    importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],   
  }